import divox2 from "./images/divox2.png";
import sightseeshare from "./images/sight-see-share.png";
import myFC from "./images/myFC.png";
import humanOrAiLogo from "./images/humanOrAiLogo.png";
import zfit from "./images/zfit.png";
import tripLogo from "./images/tripLogo.png";
import route9 from "./images/route 9 landscape 3.png";
import tech from "./images/tech-news.png";

export const ProjectsList = [
  {
    name: "divoxutils",
    image: divox2,
    skills:
      "Divoxutils is a web application inspired by the legacy of daocutils and other notable predecessors like gimpchimp. Designed to fill the gap left by daocutils, it serves as a dynamic hub for Dark Age of Camelot enthusiasts. Built using Next.js, PostgreSQL, Prisma, and TypeScript, and deployed on Vercel, this project combines robust technology with a passion for gaming.",
    link: "https://divoxutils.com/",
    github: "https://github.com/camziny/divoxutils",
  },
  {
    name: "Route 9 Landscape Products",
    image: route9,
    skills:
      "The Route 9 Landscape Products web application is a platform designed to establish a strong online presence for a landscape products store. The platform includes a customer-facing application providing up-to-date inventory, detailed product information, and a robust admin application for managing content.",
    link: "https://r9-landscape.vercel.app/",
    github: "https://github.com/camziny/r9-landscape",
  },
  {
    name: "Tech News Aggregator",
    image: tech,
    skills:
      "The Tech News Aggregator is a platform designed to provide users with the latest and most relevant technology news from various reputable sources. The platform features a user-friendly interface for browsing articles, powerful search and sorting capabilities, and SEO optimization to enhance discoverability. Additionally, the application includes unique URLs for each article and server-side rendering for improved performance and SEO.",
    link: "https://tech-news-aggregator-xi.vercel.app/",
    github: "https://github.com/camziny/article-app",
  },
  {
    name: "Sight.See.Share",
    image: sightseeshare,
    skills:
      "Sight.See.Share is a repository where users can share unique, exciting, and exceptional points of interest that they have found in their travels. This application was built using an Express, Node.js, React, and PostgreSql.",
    link: "https://sightseeshare.netlify.app/",
    github: "https://github.com/chingu-voyages/v45-tier3-team-47",
  },
  {
    name: "Human or AI",
    image: humanOrAiLogo,
    skills:
      "Full-stack web application where users can guess whether images are generated by a human or by artificial intelligence. This app was developed using a Node.js / Express back-end, React front-end, and PostgreSQL database.",
    link: "https://human-or-ai.herokuapp.com/",
    github: "https://github.com/camziny/human-or-ai",
  },
  {
    name: "z-fit",
    image: zfit,
    skills:
      "Fitness Mobile app created using React Native, useContext API, Responsive Design, and custom StyleSheet Objects.",
    link: "https://apps.apple.com/us/app/z-fit-app/id1645436117",
    github: "https://github.com/camziny/z-fit",
  },
  {
    name: "myFc",
    image: myFC,
    skills:
      "Integrated Rapid Sports API into Node.js / Express and React.js web app with PostgreSQL database, Foundation front end with custom CSS. Incorporated Ajax functionality.",
    link: "https://my-fc-app.herokuapp.com/",
    github: "https://github.com/camziny/myFC",
  },
  {
    name: "Trip",
    image: tripLogo,
    skills:
      "Collaboratively developed in React.js, focused on features such as authentication, authorization, CRUD functionality, building out internal Express APIs, API integration, and group collaboration via proper TDD and git workflows.",
    link: "https://trip-destination-evaluation.herokuapp.com/",
    github: "https://github.com/camziny/trip",
  },
];
